# Cargo.toml -- Aldaron's Device Interface / GPU / Base
# Copyright (c) 2018  Jeron A. Lau <jeron.lau@plopgrizzly.com>
# Licensed under the MIT LICENSE
#                             _        _
#                            /@\——————/@\
# .———  .                   |   o    o   |     .————      .            .
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   .
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   |
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |
#                 |        \              /                              __/
#                           ¯————————————¯

[package]
name = "adi_gpu_base"
version = "0.4.0"
authors = [
	"Jeron A. Lau <jeron.lau@plopgrizzly.com>"
]

license = "MIT"
documentation = "https://docs.rs/adi_gpu_base"
homepage = "http://plopgrizzly.com/adi_gpu_base"
repository = "https://github.com/plopgrizzly/adi_gpu_base"

readme = "README.md"
description = "Trait for implementing the adi_gpu api"
keywords = ["graphics", "trait", "base", "adi_gpu", "api"]
categories = ["hardware-support", "rendering", "template-engine"]

exclude = [
	"examples/*", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", ".gitignore",
	"_config.yml", "ISSUE_TEMPLATE.md", "icon.png", "icon.ico"
]

[dependencies]
ami = { git = "https://github.com/PlopGrizzly/ami.git" }
awi = { git = "https://github.com/PlopGrizzly/awi.git" }
